### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by SerenModz21** [SerenModz21/serenmodz.rocks#1]
- [x] Add dark mode
- [x] Fill in the footer
- [x] Add more pages and fill in the navbar (**semi done**)
- [x] Make a better description
- [x] Improve mobile responsiveness
- [x] Make a custom 404 page
- [x] Improve the design

Note: I am still learning frontend and tailwind so some stuff may be terrible or ugly.
Also, I don't find myself creative so I suck at designing.
